name = "foot-lettuce"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-05-16"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "dumb-stuff"
preview_bucket_name = "dumb-stuff"
